# Generated by Django 4.2.7 on 2023-12-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.jobtype'),
        ),
    ]
