# Generated by Django 4.2.7 on 2023-12-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_name_jobtype_job_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtype',
            old_name='JOB TYPES',
            new_name='name',
        ),
    ]
