# Generated by Django 4.2.7 on 2023-12-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_category_slug_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
