# Generated by Django 4.2.7 on 2023-12-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_job_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
