# Generated by Django 4.2.7 on 2023-12-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_job_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, max_length=50, to='jobs.tag'),
        ),
    ]
